# Generated by Django 5.0.6 on 2025-04-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
    ]
