# Generated by Django 5.0.6 on 2025-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_platformcoin_appointment_vet_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
