# Generated by Django 5.0.6 on 2025-04-15 11:34

from django.db import migrations


def add_certified_vet_emails(apps, schema_editor):
    CertifiedVet = apps.get_model('diagnosis', 'CertifiedVet')
    
    # List of common Kenyan first and last names
    names = [
        ('James', 'Mutiso'), ('Mary', 'Mwangi'), ('John', 'Njoroge'), ('Grace', 'Kariuki'),
        ('David', 'Ochieng'), ('Lucy', 'Otieno'), ('Michael', 'Kamau'), ('Alice', 'Wangari'),
        ('Stephen', 'Kibaki'), ('Christine', 'Akinyi'), ('Daniel', 'Mwania'), ('Joyce', 'Njiru'),
        ('Samuel', 'Ruto'), ('Faith', 'Kibet'), ('Joseph', 'Ndungu'), ('Catherine', 'Kimani'),
        ('Paul', 'Mwita'), ('Hellen', 'Kiplangat'), ('Brian', 'Kariuki'), ('Eunice', 'Cheruiyot'),
        ('Kevin', 'Koech'), ('Esther', 'Cherono'), ('Peter', 'Kangogo'), ('Patricia', 'Langat'),
        ('Daniel', 'Chebet'), ('Sarah', 'Sang'), ('Charles', 'Kiptum'), ('Lydia', 'Ngugi'),
        ('Abraham', 'Kariuki'), ('Betty', 'Chesang'), ('Victor', 'Kisumu'), ('Lillian', 'Mbugua'),
        ('Elvis', 'Ngugi'), ('Sandra', 'Obondo'), ('Joshua', 'Onyango'), ('Monica', 'Wamuyu'),
        ('Omar', 'Chowdhury'), ('Nina', 'Juma'), ('Dennis', 'Kiptoo'), ('Grace', 'Kihoro'),
        ('Douglas', 'Mutua'), ('Caroline', 'Kuria'), ('Felix', 'Musyoka'), ('Diana', 'Mwangi'),
        ('Richard', 'Njenga'), ('Mary', 'Njeri'), ('George', 'Kamotho'), ('Veronica', 'Mumo'),
        ('Andrew', 'Kilonzo'), ('Sophia', 'Achieng'), ('Oscar', 'Kithinji'), ('Nelly', 'Odhiambo'),
        ('Kennedy', 'Ongaya'), ('Isabel', 'Karanja'), ('Cyrus', 'Kimathi'), ('Rose', 'Odinga'),
        ('Jacob', 'Mwangi'), ('Hannah', 'Kibuchi'), ('Benjamin', 'Maina'), ('Nancy', 'Gikonyo'),
        ('Paul', 'Waweru'), ('Ruth', 'Mutava'), ('Chris', 'Ruto'), ('Jemima', 'Ochieng'),
        ('Raphael', 'Riverson'), ('Lily', 'Mariga'), ('David', 'Ndirangu'), ('Jennifer', 'Njuguna'),
        ('Tony', 'Gichuki'), ('Grace', 'Otieno'), ('Moses', 'Macharia'), ('Rebecca', 'Mwilu'),
        ('Gideon', 'Mwangi'), ('Dorcas', 'Ndegwa'), ('Sylvester', 'Ngugi'), ('Damaris', 'Nganga'),
        ('Albert', 'Karanja'), ('Carla', 'Mutindi'), ('Miriam', 'Bett'), ('William', 'Mwaura'),
        ('Amina', 'Jibril'), ('Alex', 'Gathu'), ('Hannah', 'Kiragu'), ('Felix', 'Waweru'),
        ('Jacob', 'Otieno'), ('Ruth', 'Mwathi'), ('Benson', 'Kangethe'), ('Margaret', 'Nyambura'),
        ('Bernard', 'Mwaura'), ('Grace', 'Nyambura'), ('Douglas', 'Muriithi'), ('Janet', 'Macharia'),
        ('Nelly', 'Mwangi'), ('Michael', 'Mbugua'), ('Racheal', 'Kamau'), ('Lilian', 'Obara'),
        ('Jack', 'Mutai'), ('Esther', 'Munyua'), ('Benjamin', 'Kiplagat'), ('Edith', 'Njoroge')
    ]
    
    # Create 100 certified vet emails
    for i, (first_name, last_name) in enumerate(names, start=1):
        email = f'{first_name.lower()}.{last_name.lower()}@vetmashinani.com'
        CertifiedVet.objects.create(email=email)


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RunPython(add_certified_vet_emails),
    ]
